spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jwtauth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

jwt:
  secret: n11bootcampyusufalperenbozkurt32
  access-token-expiration: 900000
  refresh-token-expiration: 604800000